export const ADD_VOTE = 'ADD_VOTE';

export const NEW_ANECDOTE = 'NEW_ANECDOTE';

export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';

export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';

export const SET_FILTER = 'SET_FILTER';
