DELETE http://localhost:3003/api/blogs/600ee06262d9383ea6e42e9a
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdGFtYXRhdGEiLCJpZCI6IjYwMDFiYmFhNWQ0YzAyMzgwODM1MGM3OCIsImlhdCI6MTYxMTIyNDU0NX0.XoDeMD93cjFwJyl45o7QWtbaQf1iG9uKltHztJhOIoE